<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="HdrHistogram" Version="2.5.0" />
    <PackageVersion Include="MessagePack" Version="3.1.11" />
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
    <PackageVersion Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>
  <ItemGroup Label="Tests">
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>
</Project>
