using System.Text.Json.Serialization;
using Comet.Content;
using Comet.ContentBuild;
using ShapeLand.Shared.Content;
using Tomlyn.Serialization;

namespace ShapeLand.ContentBuild;

/// <summary>ShapeLand's content types and rules, run through Comet's content build.</summary>
public static class ShapeLandBuild
{
    /// <summary>The test zone's heightmap, generated by the <c>terrain</c> command until the Unity editor tools exist.</summary>
    public const string TerrainPath = "zones/test/terrain.height";

    public static ContentBuilder CreateBuilder(string contentRoot) => new ContentBuilder(contentRoot)
        .Add("shape", "shapes", ShapeLandToml.Default.Shape, ValidateShape);

    /// <summary>Checks and compiles the content folder; null content means there were errors.</summary>
    public static (ShapeLandContent? Content, IReadOnlyList<ContentError> Errors) Build(string contentRoot, bool saveRegistry = true)
    {
        var result = CreateBuilder(contentRoot).Build(saveRegistry);
        var errors = result.Errors.ToList();
        var terrainFile = Path.Combine(contentRoot, TerrainPath);
        Heightmap? terrain = null;
        try
        {
            using var stream = File.OpenRead(terrainFile);
            terrain = HeightmapFormat.Read(stream);
        }
        catch (Exception e) when (e is ContentException or IOException)
        {
            errors.Add(new ContentError(terrainFile, 1, 1, e.Message));
        }

        if (errors.Count > 0 || terrain is null)
        {
            return (null, errors);
        }

        return (new ShapeLandContent(result.Entries<Shape>(), terrain), errors);
    }

    private static void ValidateShape(Shape shape, ContentValidation validation)
    {
        if (string.IsNullOrWhiteSpace(shape.DisplayName))
        {
            validation.Error(nameof(Shape.DisplayName), "must not be empty.");
        }

        if (shape.MaxSpeed is <= 0 or > 50)
        {
            validation.Error(nameof(Shape.MaxSpeed), $"{shape.MaxSpeed} is out of range (above 0, at most 50 m/s).");
        }

        if (shape.JumpVelocity is <= 0 or > 30)
        {
            validation.Error(nameof(Shape.JumpVelocity), $"{shape.JumpVelocity} is out of range (above 0, at most 30 m/s).");
        }

        ValidateLook(shape, validation);
    }

    private static void ValidateLook(Shape shape, ContentValidation validation)
    {
        var look = shape.Look;
        bool Range(string field, float value, float min, float max, bool minAllowed = false)
        {
            if (value > max || value < min || (value == min && !minAllowed))
            {
                validation.Error(nameof(Shape.Look), field, $"{value} is out of range ({(minAllowed ? "at least" : "above")} {min}, at most {max} m).");
                return false;
            }

            return true;
        }

        // Checks against the width or height only once those are valid, so one mistake gives one error.
        var widthOk = Range(nameof(ShapeLook.Width), look.Width, 0, 4);
        Range(nameof(ShapeLook.Depth), look.Depth, 0, 4);
        var heightOk = Range(nameof(ShapeLook.Height), look.Height, 0, 4);
        Range(nameof(ShapeLook.Hover), look.Hover, 0, 2, minAllowed: true);
        Range(nameof(ShapeLook.EyeWidth), look.EyeWidth, 0, 1);
        Range(nameof(ShapeLook.EyeHeight), look.EyeHeight, 0, 1);
        if (widthOk)
        {
            Range(nameof(ShapeLook.EyeSpacing), look.EyeSpacing, 0, look.Width, minAllowed: true);
        }

        if (!heightOk)
        {
            return;
        }

        Range(nameof(ShapeLook.EyeLevel), look.EyeLevel, 0, look.Height, minAllowed: true);
        if (shape.Mesh == MeshKind.Diamond)
        {
            if (look.Waist <= 0 || look.Waist >= look.Height)
            {
                validation.Error(nameof(Shape.Look), nameof(ShapeLook.Waist), $"{look.Waist} is out of range (a diamond needs one above 0 and below its height, {look.Height} m).");
            }
        }
        else if (look.Waist != 0)
        {
            validation.Error(nameof(Shape.Look), nameof(ShapeLook.Waist), "only diamonds have a waist.");
        }
    }
}

[TomlSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower)]
[TomlSerializable(typeof(Shape))]
internal partial class ShapeLandToml : TomlSerializerContext
{
}
